name: check_syntax

on:
  push:
<<<<<<< HEAD
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: [3.9, 3.10, 3.11]
        exclude:
          - os: ubuntu-latest
            python-version: "3.10"
=======
    branches: [ "check_syntax" ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, 3.10, 3.11]
>>>>>>> 04a53cd1398253f9febd9847c98919ac46a1b478

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
<<<<<<< HEAD
    - name: Update pip
      run: |
        python -m pip install --upgrade pip
    - name: Install flake8 unittest
      run: |
        python -m pip install flake8
        python -m pip install unittest
=======
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install flake8
      run: |
        python -m pip install flake8
>>>>>>> 04a53cd1398253f9febd9847c98919ac46a1b478
    - name: Display Python Version
      run: |
        python --version
    - name: Run flake8
      run: |
        flake8 .
<<<<<<< HEAD
    - name: Run unittest
      run: |
        python -m unittest discover -v
=======
>>>>>>> 04a53cd1398253f9febd9847c98919ac46a1b478
